version: '2'

services:
  # postgres:
  #   image: postgres:10-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=data

  app:
    build:
      context: .
#    depends_on:
#    - postgres
    ports:
    - 8000
    volumes:
    - .:/usr/src/app
    restart: always

# volumes:
#   pgdata:
