version: '2'

services:
  app:
    build:
      context: .
    ports:
    - 8000:8000
    volumes:
    - .:/usr/src/app
    - ~/.aws/:/root/.aws
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
