# Generated by Django 2.1.2 on 2018-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedBookPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('computed_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
